// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubmissionService.Infrastructure.Persistence;

#nullable disable

namespace SubmissionService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112071815_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubmissionService.Domain.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("languageId");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("languageName");

                    b.HasKey("LanguageId")
                        .HasName("PK__Language__12696A62150DDB19");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("SubmissionService.Domain.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ExecutionTime")
                        .HasColumnType("float");

                    b.Property<int>("MemoryUsed")
                        .HasColumnType("int");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("int");

                    b.HasKey("ResultId")
                        .HasName("PK__Results__976902083B2A0C15");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("SubmissionService.Domain.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("SubmissionId")
                        .HasName("PK__Submissi__449EE1258400B2E4");

                    b.HasIndex("LanguageId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("SubmissionService.Domain.Result", b =>
                {
                    b.HasOne("SubmissionService.Domain.Submission", "Submission")
                        .WithMany("Results")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubmissionResults_Submissions");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("SubmissionService.Domain.Submission", b =>
                {
                    b.HasOne("SubmissionService.Domain.Language", "Language")
                        .WithMany("Submissions")
                        .HasForeignKey("LanguageId")
                        .IsRequired()
                        .HasConstraintName("FK_Submissions_Languages");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("SubmissionService.Domain.Language", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("SubmissionService.Domain.Submission", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
